name: intro_flutter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.8

dependencies:
  bloc: ^8.1.2
  character_repository:
    path: packages/character_repository
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  rick_and_morty_api:
    path: packages/rick_and_morty_api

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  mocktail_image_network: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
