name: character_repository
description: Dart package for the character domain
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  rick_and_morty_api:
    path: ../rick_and_morty_api

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
