name: character_repository
description: Dart package for the character domain
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  rick_and_morty_api:
    path: ../rick_and_morty_api

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^6.0.0
