name: api_client
on:
  pull_request:
    paths:
      - "packages/api_client/**"
      - ".github/workflows/api_client.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
